version: '3'
services:
  python-app:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server.py:/app/server.py
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: mike
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: users

  mysql-db:
    container_name: mysql-db
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 654321
      MYSQL_DATABASE: users
      MYSQL_USER: mike
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data